### ISSUE TITLE
Help Wanted: Screenshots

### ISSUE THREAD

**Issue by Dukeatron** [catppuccin/glamour#2]
This repository needs a better preview screenshot to show this theme's capabilities.

**Comment by justTOBBI** [comment]
So I just looked into the topic and I think using [glow](https://github.com/charmbracelet/glow) and just fetching the catppuccin readme using
 `glow https://github.com/catppuccin/catppuccin` 
would be a good fit?

**Comment by extremepayne** [comment]
I've made one at https://raw.githubusercontent.com/extremepayne/catppuccin-glamour/main/assets/res.webp ; I'll open a PR for it once #4 is merged

**Comment by Dukeatron** [comment]
Screenshots added in recent PR, closing issue
